---
- hosts: all

  become: true
  tasks:
#    - name: Prune unused Docker objects
#      docker_system:
#        state: prune
#        remove_all: yes
    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
