---
- hosts: all

  become: true
  tasks:
    - name: Update, upgrade, autoremove, and autoclean packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
